// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mfvacqmsaudhozgogfrx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdmFjcW1zYXVkaG96Z29nZnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwNzU3NDEsImV4cCI6MjA0NzY1MTc0MX0.vb4GA9tKLhi0F_b6Gar7jTDNetUd8xfyVTHMAVN5dwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);